###########
# site.url, site.title

title: 'RecordR'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path:
url:  'https://www.recordr.download'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

#######
# Download

os:
  macos1010:
    url: "https://dl.dropboxusercontent.com/s/bea2tf6st3sijuj/RecordR_v20.5-11-ga23f36bc_MacOS10.10%2B.dmg?dl=0"
  macos1013:
    url: "https://dl.dropboxusercontent.com/s/y9xojx8p7hiihx7/RecordR_v20.5-11-ga23f36bc_MacOS10.13%2B.dmg?dl=0"
  windows:
    url: "https://dl.dropboxusercontent.com/s/uakdaow69ydvf4j/RecordR_v20.5-11-ga23f36bc.exe?dl=0"

#######
# translation

index:
  en:
  fr: index.fr.md
t:
  en:
    name: "en"
    download: "Download"
  fr:
    name: "fr"
    download: "Télécharger"

