###########
# site.url, site.title

title: 'RecordR'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path:
url:  'https://www.recordr.download'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

#######
# Download

os:
  macos:
    recordr:
      url: "https://dl.dropboxusercontent.com/s/uxtmu7gk6kqr36m/RecordR_v20.10_MacOS10.13%2B.dmg?dl=0"
    joker:
      url: "https://dl.dropboxusercontent.com/s/jqnzj1ggggu167a/Joker_v20.7.4_MacOS10.10%2B.dmg?dl=0"
  windows:
    recordr:
      url: "https://dl.dropboxusercontent.com/s/nzxmaekuuhvtouy/RecordR_v20.10.exe?dl=0"
    joker:
      url: "https://dl.dropboxusercontent.com/s/io6bisucqj97129/Joker_v20.7.4.exe?dl=0"

#######
# translation

index:
  en:
  fr: index.fr.md
t:
  en:
    name: "en"
    download: "Download"
  fr:
    name: "fr"
    download: "Télécharger"

