###########
# site.url, site.title

title: 'RecordR'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /
url:  'https://www.recordr.download'
download_url: "https://github.com/JokerSync/Joker/releases/download/v1.1.5/Joker_1.1.5_macos.dmg"

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

#######
# translation

index:
  en:
  fr: index.fr.md
t:
  en:
    name: "en"
    download: "Download"
  fr:
    name: "fr"
    download: "Télécharger"

