###########
# site.url, site.title

title: 'RecordR'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path:
url:  'https://www.recordr.download'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

#######
# Download

os:
  macos:
    recordr:
      url: "https://dl.dropboxusercontent.com/s/6dqggyfbede5dnk/RecordR_v20.2-74-g34a2280d.dmg?dl=0"
    joker:
      url: "https://dl.dropboxusercontent.com/s/jqnzj1ggggu167a/Joker_v20.7.4_MacOS10.10%2B.dmg?dl=0"
  macos1010:
    url: "https://github.com/MartinDelille/RecordR/releases/download/20.6/RecordR_v20.6_MacOS10.10+.dmg"
  macos1013:
    url: "https://github.com/MartinDelille/RecordR/releases/download/20.6/RecordR_v20.6_MacOS10.13+.dmg"
  windows:
    recordr:
      url: "https://dl.dropboxusercontent.com/s/07z27go7726w8wu/recordr_v20.2-105-0a58ef903f.exe?dl=0"
    #url: "https://github.com/MartinDelille/RecordR/releases/download/20.6/RecordR_v20.6.exe"
    joker:
      url: "https://dl.dropboxusercontent.com/s/io6bisucqj97129/Joker_v20.7.4.exe?dl=0"

#######
# translation

index:
  en:
  fr: index.fr.md
t:
  en:
    name: "en"
    download: "Download"
  fr:
    name: "fr"
    download: "Télécharger"

